var WorldMap = (function() {
  
  var Config = new Map.Config({
    size:16
  });
  
  Config.addTileset(0, Map.ALL_SAME, "w"); // 0,0
  Config.addTileset(0, Map.ALL_SAME, "w"); // 0,1
  Config.addTileset(0, Map.ALL_SAME, "w"); // 0,2
  Config.addTileset(0, Map.ALL_SAME, "w"); // 0,3
  Config.addTileset(0, Map.ALL_SAME, "w"); // 0,4
  Config.addTileset(0, Map.ALL_SAME, "w"); // 0,5
  Config.addTileset(0, Map.ALL_SAME, "w"); // 0,6
  Config.addTileset(0, Map.ALL_SAME, "w"); // 0,7
  Config.addTileset(0, Map.ALL_SAME, "w"); // 0,8
  // 0,9
  Config.addTileset(0, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwxssssssss"
                       ,"wwwwwwxsssssssss"]);
  // 0,10
  Config.addTileset(0, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"ssxwwwwwwwwwwwww"
                       ,"ssssxwwwwwwwwwww"]);
  Config.addTileset(0, Map.ALL_SAME, "w"); // 0,11
  Config.addTileset(0, Map.ALL_SAME, "w"); // 0,12
  Config.addTileset(0, Map.ALL_SAME, "w"); // 0,13
  Config.addTileset(0, Map.ALL_SAME, "w"); // 0,14
  Config.addTileset(0, Map.ALL_SAME, "w"); // 0,15
  
  // 1,0
  Config.addTileset(1, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwwx"
                       ,"wwwwwwwwwwwwwwxf"
                       ,"wwwwwwwwwwwwwxff"
                       ,"wwwwwwwwwwwwxfff"
                       ,"wwwwwwwwwwwwffff"
                       ,"wwwwwwwwwwwwffff"
                       ,"wwwwwwwwwwwxffff"]);
  // 1,1
  Config.addTileset(1, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwx       xw"
                       ,"wwwwwx       mmm"
                       ,"wwwww  mmm  mmmm"
                       ,"wwwwx mmmm  mmmm"
                       ,"wwwx mmmmmggggmm"
                       ,"wwx  mmmmggggggg"
                       ,"wx  mmmmmgggggg*"
                       ,"x   mmmmgggggggg"
                       ,"   mmmmgggggggmm"
                       ,"fffmmmmgggggggmm"
                       ,"fffmmmmmggggg*mm"
                       ,"fffmmmmmmggggggg"
                       ,"fffmmmmmmmmmgggg"
                       ,"ffffmmmmmmmmmmmm"
                       ,"fffffmmmmmmmmmmm"]);
  // 1,2
  Config.addTileset(1, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"mmmmxwwwwwwwwwww"
                       ,"mmmmmmmmmmmmmmmm"
                       ,"mmmmmmmmmmmmmmmm"
                       ,"mmmmrrrrrrmmmmmm"
                       ,"mmmrrrrrrrrrrrmm"
                       ," mmrrrrrrrrrrrrr"
                       ,"mmmrrrrrrrrrrrmm"
                       ,"mmmmmmmrrrrrrmmm"
                       ,"mmmmmmmmmmmmmmmm"
                       ,"mmmmmmmmmmmmmmmm"
                       ,"gmmmmmmmmmmmmmmm"
                       ,"gfffffmmmmmmmmmm"
                       ," fffffffmmmmmmmm"
                       ,"mmmfffffffmmmmmm"]);
  // 1,3
  Config.addTileset(1, ["wwwwwwwwwwwwx   "
                       ,"wwwwwwx      mmm"
                       ,"wwwxmmmmmmmmmmmm"
                       ,"mmmmmmmmmmmmmmmm"
                       ,"mmmmmmmmmmmmmmmm"
                       ,"mmmmmmmmmmmmmmmm"
                       ,"mmmmmmmmmmmmmmmm"
                       ,"rrrmmmmmmmmmmmmm"
                       ,"mmrrrrrmmmmmmmmm"
                       ,"mmmmmmrmmmmmmmmm"
                       ,"mmmmmmrmmmmmmmmm"
                       ,"mmmmmmrmmmmmmmmm"
                       ,"mmmmmmrmmmmmmmmm"
                       ,"mm@@@@F@mmmmmmmm"
                       ,"mmrrrrrrmmmmmmmm"
                       ,"mmrrrrrrmmmmmmmm"]);
  // 1,4
  Config.addTileset(1, ["                "
                       ,"mmmmmmmmmmmmm   "
                       ,"mmmmmmmmmmmmm   "
                       ,"mmmmmmmmmmmmxwww"
                       ,"mmmmmmmmmxwwwwww"
                       ,"mmmmmmmxwwwwwwww"
                       ,"mmmmmmxwwwwwwwww"
                       ,"mmmmmxwwwwwwwwww"
                       ,"mmmmxwwwwwwwwwww"
                       ,"mmmxwwwwwwwwwwww"
                       ,"mmxwwwwwwwwwwwww"
                       ,"m wwwwwwwwwwwwww"
                       ,"m wwwwwwwwwwwwww"
                       ,"m wwwwwwwwwwwwww"
                       ,"m wwwwwwwwwwwwww"
                       ,"mmwwwwwwwwwwwwww"]);
  // 1,5
  Config.addTileset(1, ["       xwwwwwwww"
                       ,"       xwwwwwwww"
                       ,"xwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  Config.addTileset(1, Map.ALL_SAME, "w"); // 1,6
  // 1,7
  Config.addTileset(1, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwwx"
                       ,"wwwwwwwwwwwwwwxs"
                       ,"wwwwwwwwwwwwwxff"
                       ,"wwwwwwwwwwwwxfff"
                       ,"wwwwwwwwwwwxffff"
                       ,"wwwwwwwwwwxfffff"
                       ,"wwwwwwwwwxfffffx"]);
  // 1,8
  Config.addTileset(1, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwwx"
                       ,"wwwwwwwwwwwwxsss"
                       ,"wwwwwwwwwwwxssss"
                       ,"wwwwwwwwwxffssss"
                       ,"wwwwwwwxffffssss"
                       ,"wwwwwwxffffffffs"
                       ,"wwwwwxfffffffffx"
                       ,"wxsssffffffffxww"
                       ,"sssssfffffffxwww"
                       ,"sssffffffxwwwwww"
                       ,"ffffffffxwwwwwww"
                       ,"fffffffxwwwwwwww"
                       ,"ffffffxwwwwwwxss"
                       ,"ffffxwwwwwwxssss"
                       ,"wwwwwwwwwwxsssss"]);
  // 1,9
  Config.addTileset(1, ["wwwwwxssssssssmm"
                       ,"sssssssssssmmmmm"
                       ,"sssssssssssmmmmm"
                       ,"sssssssssxwwwwww"
                       ,"ssssssssxwwwwwww"
                       ,"ssssssxwwwxfffff"
                       ,"sssxwwwwxfffffff"
                       ,"wwwwwwwxffffffff"
                       ,"wwwwwwxfffffffff"
                       ,"wwwwwwffffffffff"
                       ,"wwwwwxffffffffff"
                       ,"wwwxsssssssssmmm"
                       ,"wxssssssssssmmmm"
                       ,"ssssssssssmmmmmm"
                       ,"ssssssssmmmmmmmm"
                       ,"sssssssmmmmmmmmm"]);
  // 1,10
  Config.addTileset(1, ["mmssssssssmmxwww"
                       ,"mmmmssssssmmmxww"
                       ,"mmmmmsssssmmmmxw"
                       ,"wxmmmssssssmmmmx"
                       ,"ww6mmsssssssmmmm"
                       ,"ffffffssssssmmmm"
                       ,"ffffffssssmmmmmm"
                       ,"fffffmmmmmmmmmmm"
                       ,"ffffmmmmmmmmmmmm"
                       ,"fffmmmmmmmmmmmmm"
                       ,"fffmmmmmmmmmmmmm"
                       ,"mmdddddddmmmmmmm"
                       ,"mmddddddddddddmm"
                       ,"mmdddddddddddddm"
                       ,"mmdddddddddddddm"
                       ,"mmdddddddddddddd"]);
  // 1,11
  Config.addTileset(1, ["wwwwwwwwwwwwwwww"                        
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"xwwwwwwwwwwwwwww"
                       ,"mwwwwwwwwwwwwwww"
                       ,"mxwwwwwwwwwwwwww"
                       ,"mmwwwwwwwwwwwwww"
                       ,"mmxwwwwwwwwwwwww"
                       ,"mmmmxwwwwwwwwwww"
                       ,"mmmm wwwwwwwwwww"
                       ,"mmmmxwwwwwwwwwww"
                       ,"mmmxwwwwwwwwwwww"
                       ,"mmmwwwwwwwwwwwww"
                       ,"mmmwwwwwwwwwwwww"]);
  // 1,12
  Config.addTileset(1, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwwx"
                       ,"wwwwwwwwwwwwwwwm"]);
  // 1,13
  Config.addTileset(1, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwxmmm"
                       ,"wwwwwwwwwwwxmmmm"
                       ,"wwwwxmmxwxmmmmmm"
                       ,"wwwxmmmmmmmmmmvv"
                       ,"wxmmmmmmmmmmmvvm"
                       ,"xmmmmmmmmmmmg`mm"
                       ,"mmmxxmmmmmmggmmm"
                       ,"mmxwxmmmggggmmmm"]);
  // 1,14
  Config.addTileset(1, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwx     "
                       ,"wwwwwwwwwx      "
                       ,"wwwwwwx mm      "
                       ,"wwwwwxmmmm      "
                       ,"wwwxmmmm       x"
                       ,"xmmmmmm    xwwww"
                       ,"mmmmmmm   xwwwww"
                       ,"mmmmmm  xwwwwwww"
                       ,"@mmmm  xwwww82ww"
                       ,"#mmxwwwwwwwxxwww"
                       ,"mmxwwwx xx xwwww"
                       ,"mxwwx     xwwwww"
                       ,"mxwx  xx xwwwwww"
                       ,"mm   xwwwwwwwwww"]);
  // 1,15
  Config.addTileset(1, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"xwwwwwwwwwwwwwww"
                       ,"  xwwwwwwwwwwwww"
                       ,"   xwwwwwwwwwwww"
                       ,"    wwwwwwwwwwww"
                       ,"wwx xwwwwwwwwwww"
                       ,"wwwx wwwwwwwwwww"
                       ,"wwww62wwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  // 2,0
  Config.addTileset(2, ["wwwwwwwwwwwfffff"
                       ,"wwwwwwwwwwwfffff"
                       ,"wwwwwwwwwwwfffff"
                       ,"wwwwwwwwwwwxffff"
                       ,"wwwwx  7wwwwxfff"
                       ,"wwwx  x1wwwwwfff"
                       ,"wx   xwwwwwwwfff"
                       ,"w  xwwwwwwwwwfff"
                       ,"w  wwwwwwwwwxfff"
                       ,"w  wwwwwwwwwffff"
                       ,"w xwwwwwwwwwffff"
                       ,"w wwwwwwwwwxffff"
                       ,"w xwwwwwwwxfffff"
                       ,"w  wwwwwwxfffffx"
                       ,"w  xwwwwxffffxww"
                       ,"wx  xwx  ffxwwww"]);
  // 2,1
  Config.addTileset(2, ["ffffffmmmmmmmmmm"
                       ,"ffffffmmmmmmmmmm"
                       ,"ffffffmmmmmmmmmm"
                       ,"fffffffmmmmmmmmm"
                       ,"ffffffffmmmmmmmm"
                       ,"ffffffffxwwwwxmm"
                       ,"fffffffxwwwwwwxm"
                       ,"ffffffxwwwwwwww "
                       ,"fffffxwwwwwwwwwm"
                       ,"fffxwwwwwwwwwwxm"
                       ,"ffxwwwwwwwwwwxmm"
                       ,"fxwwwwwwwwwwxmmm"
                       ,"xwwwwwwwwwxmmmmm"
                       ,"wwwwwwwwxmmmmmmm"
                       ,"wwwwwwwxmmmmmmmm"
                       ,"wwwxmmmmmmmmmmmm"]);
  // 2,2
  Config.addTileset(2, ["mmmmffffffffmmmm"
                       ,"mmmmmffffffffmmm"
                       ,"mmmmmffffffffffm"
                       ,"mmmmmffffffffffm"
                       ,"mmmmmffffffffffm"
                       ,"mmmmfffffffffffm"
                       ,"mmmmfffffffffffm"
                       ,"mmmmffffffffffff"
                       ,"mmmmffffffffffff"
                       ,"mmmmmfffffffffff"
                       ,"mmmmmmffffffffff"
                       ,"mmmmmmmfffffffff"
                       ,"mmmmmmmmffffffff"
                       ,"mmmmmmmmmfffffff"
                       ,"mmmmmmmmmmffffff"
                       ,"mmmmmmmmmmmmffff"]);
  // 2,3
  Config.addTileset(2, ["mmrrrrrrmmmmmmmm"
                       ,"mmmrrrmmmmmmmmmm"
                       ,"mmmmrmmmmmmmmmmm"
                       ,"mmmmrmmmmmmmmmmm"
                       ,"mmmmrmmmmmmmmmmm"
                       ,"mmmmrmmmmmmmmmmm"
                       ,"mmmmrmmmmmmmmmmm"
                       ,"fmmmrrrrrmmmmmmm"
                       ,"fmmmmmmmrmmmmmmm"
                       ,"fmmmmmmmrmmmmmmm"
                       ,"fmmmmmmmrmmmmmmm"
                       ,"fffmmmmmrrrrmmmm"
                       ,"ffffmmmmmmmrmmmm"
                       ,"ffffmmmmmmmrmmmm"
                       ,"fffffmmmmmmrmmmm"
                       ,"mffffmmmmmrrmmmf"]);
  // 2,4
  Config.addTileset(2, ["mmxwwwwwwwwwwwww"
                       ,"mmmwwwwwwwwwwwww"
                       ,"mmmxwwwwwwwwwwww"
                       ,"mmmmxwwwwwwwwwww"
                       ,"mmmmmmxwwwwwwwww"
                       ,"mmmmmmmmmxwwwwww"
                       ,"mmmmmmmmmmxwwwww"
                       ,"mmmmmmmmmm xwwww"
                       ,"mmmmxwwwwx  xwww"
                       ,"mmmxwwwwwwwx xww"
                       ,"mmxwwwwwwwwww62w"
                       ,"mmwwwwwwwwwwwwww"
                       ,"mmxwwwwwwwwww37w"
                       ,"fffxwwwwwwwwww w"
                       ,"ffffxwwwwwwwww w"
                       ,"fffffxwwwwwwww x"]);
  // 2,5
  Config.addTileset(2, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwww4wwwwwww"
                       ,"wwwwwwww6 ffxwww"]);
  Config.addTileset(2, Map.ALL_SAME, "w"); // 2,6
  // 2,7
  Config.addTileset(2, ["wwwwwwwwxffffxww"
                       ,"wwwwwwwxffffxwww"
                       ,"wwwwwwxffffxwwww"
                       ,"wwwwwx fffxwwwww"
                       ,"wwwwwx  xwwwwwwx"
                       ,"wwwwwwwwwwwwwxff"
                       ,"wwwwwwwwwwwwxfff"
                       ,"wwwwwwwwwwwxfffm"
                       ,"wwwwwwwwwwwffffm"
                       ,"wwwwwwwwwwwfffff"
                       ,"wwwwwwwwwwwxffff"
                       ,"wwwwwwwwwwwwfffs"
                       ,"wwwwwwwwwwwwxmms"
                       ,"wwwwwwwwwwwwwmms"
                       ,"wwwwwwwwwwwwwmms"
                       ,"wwwwwwwwwwwwwmmm"]);
  // 2,8
  Config.addTileset(2, ["wwwwwwwwwxsssmmm"
                       ,"wwwxssrfffssmmmm"
                       ,"wwx:rrrffffmmmmm"
                       ,"wxffrffffffmmmmf"
                       ,"ffffrfffffmmmmff"
                       ,"ffffrrrrmmmmmmff"
                       ,"ffffmmmrmmmmmfff"
                       ,"mmmmmmmrmmmmffff"
                       ,"mmmmmmrrrmmmffff"
                       ,"mmmmmmrrrmmmffff"
                       ,"ssssmmmmmmmffffx"
                       ,"sssssmmmmmmfffxw"
                       ,"sCCsssmmmmmffxww"
                       ,"sCCsssxwwwwwwwww"
                       ,"sssssswwwwwwwwww"
                       ,"sssssswwwwwwwwww"]);
  // 2,9
  Config.addTileset(2, ["mfffmmmmmmmmmmmm"
                       ,"mfffmmmmmmfffffm"
                       ,"ffffmmmmmfffffff"
                       ,"fffxwwx  fffffff"
                       ,"ffxwwwwwwwxfffff"
                       ,"ffwwwwwwwwwxffff"
                       ,"ffwwwwwwwwwwxfff"
                       ,"fxwwwwwwwwwwwwww"
                       ,"fwwwwwwwwwwwwwww"
                       ,"xwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  // 2,10
  Config.addTileset(2, ["mmmddddddddddddd"
                       ,"mmmmmmmddddddddd"
                       ,"mmmmmmmmmmmddddd"
                       ,"fmmmmmmmmmmmmmmf"
                       ,"ffffmmmmmmmmmmmf"
                       ,"fffffffmmmmmmmmf"
                       ,"ffffffffffffffff"
                       ,"wwwwwxffffffffff"
                       ,"wwwwwwxfffffffff"
                       ,"wwwwwwwxffffffff"
                       ,"wwwwwwwxffffffff"
                       ,"wwwwwww fffffffx"
                       ,"wwwwwwwxfffffffw"
                       ,"wwwwwwwwxfffffxw"
                       ,"wwwwwwwwwxfffxww"
                       ,"wwwwwwwwwwwwwwww"]);
  // 2,11
  Config.addTileset(2, ["fffwwwwwwwwwwwww"
                       ,"fffwwwwwwwwwwwww"
                       ,"fffxwwwwwwwwwwww"
                       ,"ffffxwwwwwwwwwww"
                       ,"fffffffffxwwwwww"
                       ,"ffffffffffgggggg"
                       ,"ffffffffff~ggggg"
                       ,"ffffffffffgg*xww"
                       ,"ffx18mmmmggggwww"
                       ,"fxwxmmmmm~ggxwww"
                       ,"xwxmmmmmmgg*wwww"
                       ,"wwxmmmmggggGwwww"
                       ,"wwwmmm&gggg`wwww"
                       ,"wwwxmmmgggg*xwww"
                       ,"wwwwmmmmmggg*xww"
                       ,"wwwxmmmmmmmmmmmm"]);
  // 2,12
  Config.addTileset(2, ["wwwwwwwwwwwwwwwm"
                       ,"wwwwwwwwwwwwwwwx"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"xwwwwwwwwwwwwwww"
                       ," 7wwwwwwwwwwwwww"
                       ,"w1w4wwwwwwwwwwww"
                       ,"www6 xwwwwwwwwww"
                       ,"wwww  mmmmmmmmmm"
                       ,"wwww mmmmmmmmmmm"
                       ,"wwwxmmmmmmmmmmmm"
                       ,"wwwmmmmmmdddddmm"
                       ,"wwxmmmmmmddddddd"
                       ,"xmmmmmmmdddddddd"
                       ,"mmmmmddddddddddd"]);
  // 2,13
  Config.addTileset(2, ["mxwxmmmgggmmmmmm"
                       ,"xwxmmmggmmmmmmmm"
                       ,"wxmmm&gmmmmmmmmm"
                       ,"xmmmmmmmmmmmmmmm"
                       ," mmmmmmmmmmmmmmx"
                       ," mmmmmmmmmmmmmxw"
                       ,"xmmmmmmmmmmmmxww"
                       ,"wxmmmmmmmmmxwwww"
                       ,"wxmmmmmmmmxwwwww"
                       ,"mmmmmxxmmxwwwwww"
                       ,"mmmmxwwxxwwwwwww"
                       ,"mmmmxwwwwwwwwwww"
                       ,"mmmmmxwwwwwwwwww"
                       ,"mmmmmmxwwwwwwwww"
                       ,"dmmmmmmxwwwwwwww"
                       ,"dmmmmmmmxwwwwwww"]);
  
  // 2,14
  Config.addTileset(2, ["mmxwwwwwwwwwwwww"
                       ,"mxwwwwwwwwwwwwww"
                       ,"xwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  Config.addTileset(2, Map.ALL_SAME, "w"); // 2,15
  // 3,0
  Config.addTileset(3, ["wwx     xwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwwx"
                       ,"wwwwwwwwwwwwwwxm"
                       ,"wwwwwwwwwwwwwxmm"
                       ,"wwwwwwwwwwwww mm"
                       ,"wwwwwwwwwwwww mm"
                       ,"wwwwwwwwwwwwwfff"
                       ,"wwwwwwwwwwwwwfff"
                       ,"wwwwwwwwwwwwwfff"
                       ,"wwwwwwwwwwwwwxff"
                       ,"wwwwwwwwwwwwwwxf"
                       ,"wwwwwwwwwwwwwwwx"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  // 3,1
  Config.addTileset(3, ["wwxmmmmmmmmmmVVf"
                       ,"xmmmmmmmmmmmVVVf"
                       ,"mmmmmmddddddVVff"
                       ,"mmmmdddddddddfff"
                       ,"mmmddddddddddffd"
                       ,"mmddddddddddd=+d"
                       ,"m dddddddddddddd"
                       ,"ffdddddddddddddd"
                       ,"ffdddddddddddddd"
                       ,"ffdddddddddddddd"
                       ,"fffddddddddddddd"
                       ,"ffffdddddddddddd"
                       ,"fffffddddddddddd"
                       ,"xfffffdddddddddd"
                       ,"wxfffffddddddddd"
                       ,"wwxfffffdddddddd"]);
  // 3,2
  Config.addTileset(3, ["fddddmmmmmmmmmmm"
                       ,"fdddddddmmmmmmmm"
                       ,"fddddddddmmmmmmm"
                       ,"dddddddddddmmmmm"
                       ,"ddddddddddddmmmm"
                       ,"ddddddddddddmmmm"
                       ,"ddddddddddddmmmm"
                       ,"ddddddddddddmmmm"
                       ,"ddddddddddddmmmm"
                       ,"ddddddddddddmmmm"
                       ,"dddddddddddmmmmm"
                       ,"ddddddddddmmmmmm"
                       ,"dddddddmmmmmmmmm"
                       ,"ddddddmmmmmmmmmm"
                       ,"ddddddmmmmmmmmmf"
                       ,"ddddddmmmmmmmmmf"]);
  // 3,3
  Config.addTileset(3, ["mmffffmmmmrmmmmf"
                       ,"mmfffffmmmrmmmmf"
                       ,"mmmffffmmmrmmmff"
                       ,"mmmfffffmmrmmmff"
                       ,"mmmmffffmmrmmmff"
                       ,"mmmmfffrrrrmmfff"
                       ,"mmmmfffrmmmmmffx"
                       ,"mmmmfffrmmmmfffw"
                       ,"mmmffffrmmmffffw"
                       ,"mmmffffrmmmffvvw"
                       ,"mmmffffrmmmffvvw"
                       ,"mmmffffrmmmfffxw"
                       ,"mmfffffrmmmfffww"
                       ,"fffffrrrmmffffww"
                       ,"fffffrffffffffww"
                       ,"fffffrffffffffxw"]);
  // 3,4
  Config.addTileset(3, ["ffffffwwwwwwwwgg"
                       ,"ffffffwwwwwwwwgo"
                       ,"ffffffwwwwwwwwx~"
                       ,"fffffxwwwwwwwww&"
                       ,"ffxwwwwwwwwwwwwg"
                       ,"xwwwwwwwwwwwwwwx"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  // 3,5
  Config.addTileset(3, ["xwwwwwwwwxffoxww"
                       ,"gwwwwwwwwwxffffx"
                       ,"`wwwwwwwwwwxffff"
                       ,"*wwwwwwwwwwwxfff"
                       ,"gwwwwwwwwwwwwwxf"
                       ," xwwwwwwwwwwwwwx"
                       ,"x xwwwwwwwwwwwww"
                       ,"wx 7wwwwwwwwwwww"
                       ,"www1w4wwwwwwwwww"
                       ,"wwwww6,sssssssxw"
                       ,"wwwwwwwwxssssosx"
                       ,"wwwwwwwwwwwxssss"
                       ,"wwwwwwwwwwwwwxss"
                       ,"wwwwwwwwwwwwwwxs"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  // 3,6
  Config.addTileset(3, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"xwwwwwwwwwwwwwww"
                       ,"oxwwwwwwwwwwwwww"
                       ,"fffxwwwwwwwwwwww"
                       ,"fff 7wwwwwwwwwww"
                       ,"wwww1wwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwww4wwwwwwww"
                       ,"wwwwwww6 xwwwwww"
                       ,"xwwwwwwwxoxwwwww"
                       ,"ssxwwwwwwx 7wwww"
                       ,"sssssxwwwww1wwww"
                       ,"wxsss 7wwwwwwwww"
                       ,"wwwwww1wwwwwwwww"]);
  // 3,7
  Config.addTileset(3, ["wwwwwwwwwwwwwmmm"
                       ,"wwwwwwwwwwwwwmmm"
                       ,"wwwwwwwwwwwwwmmm"
                       ,"wwwwwwwwwwwwwxmm"
                       ,"wwwwwwwwwwwwwwxm"
                       ,"wwwwwwwwwwwwwwwm"
                       ,"wwwwwwwwwwwwwwwx"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwwx"
                       ,"wwwwwwwwwwwwww35"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwww82www"
                       ,"wwwwwwwwwx xwwww"]);
  // 3,8
  Config.addTileset(3, ["mmmmmwwwwwwwwwww"
                       ,"mmmmmwwwwwwwwwww"
                       ,"mmmmxwwwwwwwwwww"
                       ,"mmmxwwwwwwwwwwww"
                       ,"mmmwwwwwwwwwwwww"
                       ,"mmmwwwwwwwwwwwww"
                       ,"mmmwwwwwwwwwwwww"
                       ,"mmmwwwwwwwwwwwww"
                       ,"mmxwwwwwwwwwwwww"
                       ," xwwwwwwwwwwwwww"
                       ,"xwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  // 3,9
  Config.addTileset(3, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwwx"
                       ,"wwwwwwwwwwwwwwwm"
                       ,"wwwwwwwwwwwwwwwm"
                       ,"wwwwwwwwwwwwwwwx"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  // 3,10
  Config.addTileset(3, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwxmm"
                       ,"wwwxmmmmmmmmmmmm"
                       ,"wwxmmmmmmmmmmmmm"
                       ,"wwmmmmmmmmmmmmmm"
                       ,"wxmmmmmmmmmmmddd"
                       ,"xmmmmmmmmmmmdddd"
                       ,"mmmmmmmmmmmmdddd"
                       ,"mmmmmmmmmmmmdddd"
                       ,"mmmmmmmmmmmmdddd"
                       ,"mmmmmmmmmmmmdddd"
                       ,"xmmmmmmmmmmmdddd"
                       ,"wwxmmmmmmmmmdddd"]);
  // 3,11
  Config.addTileset(3, ["www mmmmmmmmmmmm"
                       ,"wwxmmmmmmmmmmmmm"
                       ,"ww mmmmmdddddddd"
                       ,"wxmmmmmddddddddd"
                       ,"mmmmmmdddddddddd"
                       ,"mmmmmddddddddddd"
                       ,"mmmddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"]);
  // 3,12
  Config.addTileset(3, ["mmdddddddddddddd"
                       ,"mddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddm"
                       ,"dddddddddddddddm"
                       ,"dddddddddddddddm"
                       ,"ddMMdddddddddddm"
                       ,"ddMMdddddddddddm"
                       ,"dddddddddddddddm"
                       ,"dddddddddddddddm"
                       ,"dddddddddddddddm"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"]);
  // 3,13
  Config.addTileset(3, ["ddmmmmmmffxwwwww"
                       ,"ddmmmmmmfffffxww"
                       ,"ddmmmmmmffffffxw"
                       ,"dmmmmmmfffffffff"
                       ,"mmmmm ffffffffff"
                       ,"mmmmffffffffffff"
                       ,"mmmffffffrrrrrrf"
                       ,"mmfffffffrrrrrrr"
                       ,"mmfffffffrrrrrrr"
                       ,"mmfffffffrrrrrrr"
                       ,"mmfffffffffrrrrr"
                       ,"mmffffffffffffff"
                       ,"mmmfffffffffffff"
                       ,"mmmmffffffffffff"
                       ,"mmmmmfffffffffff"
                       ,"dmmmmmmffffffffx"]);
  // 3,14
  Config.addTileset(3, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"fffxwwwwwwwwwwww"
                       ,"ffffffxwwwwwwwww"
                       ,"fffffffxwwwwwwww"
                       ,"ffffffffwwwwwwww"
                       ,"rfffffffxwwwwwww"
                       ,"rffffffffxwwwwww"
                       ,"rfffffffffffxwww"
                       ,"rffffffffffffwww"
                       ,"fffffffffffffxww"
                       ,"ffffffffffffffxw"
                       ,"fffffffffffffffx"
                       ,"ffffxwxfffffffff"
                       ,"wwwwwwwwwxffffff"]);
  // 3,15
  Config.addTileset(3, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"xwwwwwwwwwwwwwww"]);
  Config.addTileset(4, Map.ALL_SAME, "w"); // 4,0
  // 4,1
  Config.addTileset(4, ["wwwxfffffddddddd"
                       ,"wwwwxfffffffdddd"
                       ,"wwwwwxffffffffff"
                       ,"wwwwwwffffffffff"
                       ,"wwwwwwxfffffffff"
                       ,"wwwwwwwxffffffff"
                       ,"wwwwwwwwxfffffff"
                       ,"wwwwwwwwwxssssss"
                       ,"wwwwwwwwwwssssss"
                       ,"wwwwwwwwww fffff"
                       ,"wwwwwwwwwwffffff"
                       ,"wwwwwwwwwwffffff"
                       ,"wwwwwwwwwwffffff"
                       ,"wwwwwwwwwwffffff"
                       ,"wwwwwwwwwwxfffff"
                       ,"wwwwwwwwwwwfffff"]);
  // 4,2
  Config.addTileset(4, ["ddddd  mmmmmmmmf"
                       ,"dddfffffmmmmmmmm"
                       ,"fffffffffmmmmmmm"
                       ,"ffffffffffffmmmm"
                       ,"fffffffffffffmmm"
                       ,"ffffffffffffffmm"
                       ,"ffffffffffffffmm"
                       ,"sssffffffffffmmm"
                       ,"sssssssssssssmmm"
                       ,"sssssssssssssmmm"
                       ,"fsssssssssssssmm"
                       ,"ffsrrrrrrrrrrrrr"
                       ,"ffsrsssssssmmmmf"
                       ,"frrrssssssmmmmmf"
                       ,"ffsssssssmmmmmmm"
                       ,"ffsssssssmmmmmmm"]);
  // 4,3
  Config.addTileset(4, ["fffffrfffffffffx"
                       ,"fffffrffffffffff"
                       ,"mffffrfffxwwxfff"
                       ,"mffffrffxwwwwwww"
                       ,"mffffrffwwwwwwww"
                       ,"mmfffrffxwwwwwww"
                       ,"mmfffrfffxwwwwww"
                       ,"mmfffrffffwwwwww"
                       ,"mfffrrffffwwwwww"
                       ,"mfffrfffffxwwwww"
                       ,"mfffrffffffwwwww"
                       ,"rrrrrffffffxwwww"
                       ,"ffffffffffffxwww"
                       ,"ffffffffffffxwww"
                       ,"fffffxwwwwwwwwww"
                       ,"xwwwwwwwwwwwwwww"]);
  // 4,4
  Config.addTileset(4, ["wwwwwwwwwwwwwwww"
                       ,"xwwwwwwwwwwwwwww"
                       ,"xwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  Config.addTileset(4, Map.ALL_SAME, "w"); // 4,5
  // 4,6
  Config.addTileset(4, ["wwwwwwwww4wwwwww"
                       ,"wwwwwwwww6 xwwww"
                       ,"wwwwwwwwwwx  fff"
                       ,"wwwwwwwwwwwx fff"
                       ,"wwwwwwwwwwwwwwxf"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  // 4,7
  Config.addTileset(4, ["wwwxffff  xwwwww"
                       ,"wwxfffff xwwwwww"
                       ,"ffffoffxwwwwwwww"
                       ,"ffffffxwwwwwwwww"
                       ,"fffffxwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  Config.addTileset(4, Map.ALL_SAME, "w"); // 4,8
  Config.addTileset(4, Map.ALL_SAME, "w"); // 4,9
  // 4,10
  Config.addTileset(4, ["wwwwwxmmmmmmdddd"
                       ,"wwwwwwxmmmmmmddd"
                       ,"wwwwwww mmmmmddd"
                       ,"wwwwwwwx mmmmmdd"
                       ,"wwwwwwww mmmmmdd"
                       ,"wwwwwwwwxmmmmmdd"
                       ,"wwwwwwwwwxmmmmdd"
                       ,"wwwwwwwwwwxmmmdd"
                       ,"wwwwwwwwwwxmmmdd"
                       ,"wwwwwwwwwxmmmddd"
                       ,"wwwwwwwwxmmmmddd"
                       ,"wwwwwwwx mmmmddd"
                       ,"wwwwwwx  mmmmddd"
                       ,"wwww8    mmmmmmd"
                       ,"wwww1wwwwxmmmmmm"
                       ,"wwwwwwwwwwwxmmmm"]);
  // 4,11
  Config.addTileset(4, ["dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"mmmmmmmmmddddddd"]);
  Config.addTileset(4, Map.ALL_SAME, "d"); // 4,12
  // 4,13
  Config.addTileset(4, ["ddmmmmmmffffffxw"
                       ,"ddmmmmmmmffffxww"
                       ,"dddmmmmmmmffxwww"
                       ,"ddd mmmmmmmmxwww"
                       ,"dddmmmmmmmmmmmxw"
                       ,"ddmmmmmmmmmmmmmx"
                       ,"ddmmmmmmmmmmmmmx"
                       ,"dmmmmmxwwwwwwwww"
                       ,"mmmmmxwwwwwwwwww"
                       ,"mmmmxwwwwwwwwwww"
                       ,"mmmmwwwwwwwwwwww"
                       ,"dmmmxwwwwwwwwwww"
                       ,"ddmmmmxwwwwwwwww"
                       ,"dddmmmmmmxwwwwww"
                       ,"dddd mmmmmxwwwww"
                       ,"ddddd mmmm wwwww"]);
  // 4,14
  Config.addTileset(4, ["wwwwwwwwwwwfffff"
                       ,"wwwwwwwwwwxsssff"
                       ,"wwwwwwwwwwsssssf"
                       ,"wwwwwwwwwwssssss"
                       ,"wwwwwwwwwwxsssss"
                       ,"wwwwwwwwwwwsssss"
                       ,"wwwwwwwwwwwxssff"
                       ,"wwwwwwwwwwwwffff"
                       ,"wwwwwwwwwwwxffff"
                       ,"wwwwwwwwwwxfffff"
                       ,"wwwwwwwwxffffffs"
                       ,"wwwwwwwxffffffss"
                       ,"wwwwwxffffffssss"
                       ,"wwwwwffffffsssss"
                       ,"wwwwwfffffssssss"
                       ,"wwwwwxffffssssss"]);
  // 4,15
  Config.addTileset(4, ["fxwwwwwwwwwwwwww"
                       ,"ffffxwwwwwwwwwww"
                       ,"fffffwwwwwwwwwww"
                       ,"fffffwwwwwwwwwww"
                       ,"fffffxwwwwwwwwww"
                       ,"ffffffwwwwwwwwww"
                       ,"ffffffwwwwwwwwww"
                       ,"fffffxwwwwwwwwww"
                       ,"ffffxwwwwwwwwwww"
                       ,"ffffwwwwwwwwwwww"
                       ,"sssswwwwwwwwwwww"
                       ,"sssswwwwwwwwwwww"
                       ,"ssssxwwwwwwwwwww"
                       ,"sssssxwwwwwwwwww"
                       ,"sssssxwwwwwwwwww"
                       ,"sssxwwwwwwwwwwww"]);
  Config.addTileset(5, Map.ALL_SAME, "w"); // 5,0
  // 5,1
  Config.addTileset(5, ["wwwwwwwwwww ffff"
                       ,"wwwwwwwwwww  ggg"
                       ,"wwwwwwwwwwwggggg"
                       ,"wwwwwwwwwwwggggg"
                       ,"wwwwwwwwwwwggggg"
                       ,"wwwwwwwwwwxggggg"
                       ,"wwwwwwwwwxmmmmmm"
                       ,"wwwwwwwwxmmmmmmm"
                       ,"wwwwwwww mmmmmmm"
                       ,"wwwwwwwwxmmmmmmm"
                       ,"wwwwwwwwwxmmmmmm"
                       ,"wwwwwwwwwwxmmmmm"
                       ,"wwwwwwwwwwwxmmmm"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  // 5,2
  Config.addTileset(5, ["f ssssssmmmmmmmx"
                       ,"gggggg mmmmmmmxw"
                       ,"ggggggmmmmmmmmww"
                       ,"gggggmmmmmmmmmww"
                       ,"ggmmmmmmmmmmmmww"
                       ,"gmmmmmmmmmmmmmww"
                       ,"mmmmmmmmmmmmmmww"
                       ,"mmmmmmmmmmmmmmww"
                       ,"mmmmmmmmmmmmmmww"
                       ,"mmmmmmmmmmmmmmxw"
                       ,"mmmmmmmmmmmmmmmx"
                       ,"mmmmmmmmmmmmmmmm"
                       ,"mmmmmmmmmmmmmmmm"
                       ,"xmmmmmmmmmmmmmmm"
                       ,"wwwwxmmmmmmmmmmm"
                       ,"wwwwwwwwwxmmmmmm"]);
  // 5,3
  Config.addTileset(5, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"xwwwwwwwwwwwwwww"
                       ,"mmxwwwwwwwwwwwww"
                       ,"mmmxwwwwwwwwwwww"
                       ,"mmmmmmxwwwwwwwww"
                       ,"mmmmmmmmmmmmxwww"]);
  Config.addTileset(5, Map.ALL_SAME, "w"); // 5,4
  Config.addTileset(5, Map.ALL_SAME, "w"); // 5,5
  Config.addTileset(5, Map.ALL_SAME, "w"); // 5,6
  Config.addTileset(5, Map.ALL_SAME, "w"); // 5,7
  Config.addTileset(5, Map.ALL_SAME, "w"); // 5,8
  Config.addTileset(5, Map.ALL_SAME, "w"); // 5,9
  // 5,10
  Config.addTileset(5, ["wwwwwwwwwwwwxmmm"
                       ,"wwwwwwwwwwwwwxmm"
                       ,"wwwwwwwwwwwwwwxm"
                       ,"wwwwwwwwwwwwwwwx"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  // 5,11
  Config.addTileset(5, ["mmmmmmmmmmmmdddd"
                       ,"mmm^ mmmmmmmmddd"
                       ,"mmm$ xwxmmmmmmdd"
                       ,"mmmmmwwwwwxmmmmd"
                       ,"xmmmmwwwwwwmmmmm"
                       ,"wxmmmwwwwwwmmmmm"
                       ,"wwmmmwwwwwwxmmmm"
                       ,"wwxmmxwwwwwwx  m"
                       ,"wwwx  xwwwwwwwwx"
                       ,"wwwwx  xwwwwwwww"
                       ,"wwwwwx  wwwwwwww"
                       ,"wwwwwww67wwwwwww"
                       ,"wwwwwwww62wwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwww4wwx"
                       ,"wwwwwwwwwwww6   "]);
  // 5,12
  Config.addTileset(5, ["dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"dddddddddddddddd"
                       ,"mmmmmmmm/ddddddd"
                       ,"mmmmmmmm+ddddddd"
                       ,"mmmmdddddddddddd"
                       ,"mmmddddddddddddd"
                       ,"mmmddddddddddddd"
                       ,"mmmdddddddddddmm"
                       ,"mmmmmddddddddmmm"
                       ,"mmmmmmddddddmmmx"
                       ,"xmmmmmmmmmmmmmmw"
                       ,"xmmmmmmmmmmmmmmw"
                       ,"mmmmmmmmmmmmmmmw"
                       ,"mmmxwwxmmmmmmmxw"]);
  // 5,13
  Config.addTileset(5, ["ddddddmmmmxwwwww"
                       ,"ddddddmmmxwwwwww"
                       ,"ddddddmmmwwwwwww"
                       ,"ddddddmmmwwwwwww"
                       ,"ddddddmmmwwwwwww"
                       ,"dddddmmmmwwwwwww"
                       ,"dddddmmmxwwwwwww"
                       ,"dd mmmmmwwwwwwww"
                       ,"dmmmmmmmwwwwwwww"
                       ," mmmmmm xwwwwwww"
                       ,"         xwwwwww"
                       ,"wwwwwwx   xwwwww"
                       ,"wwwwwww65w62wwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  // 5,14
  Config.addTileset(5, ["wwwwwwxfffssssss"
                       ,"wwwwwwxffffssssx"
                       ,"wwwwwxfffffssxww"
                       ,"wwwwwffffffsxwww"
                       ,"wwwwxffffffxwwww"
                       ,"wwwwfffffffwwwww"
                       ,"wwwwfffffffxwwww"
                       ,"wwwwffffffffwwww"
                       ,"wwwxffffffffwwww"
                       ,"wwwfffffffffwwww"
                       ,"wwwfffffffffwwww"
                       ,"wwwxffffffffxwww"
                       ,"wwwwwxfffffffxww"
                       ,"www87wwwxfffffff"
                       ,"wwwffxwwwxffffff"
                       ,"wwwfffxwwwxfffff"]);
  // 5,15
  Config.addTileset(5, ["xwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"xwwwwwwwwwwwwwww"
                       ,"fxwwwwwwwwwwwwww"
                       ,"ffwwwwwwwwwwwwww"]);
  Config.addTileset(6, Map.ALL_SAME, "w"); // 6,0
  Config.addTileset(6, Map.ALL_SAME, "w"); // 6,1
  // 6,2
  Config.addTileset(6, ["wwwwwwwwwwwwwwwx"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  // 6,3
  Config.addTileset(6, ["mmmmmmmmmmmmxwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  Config.addTileset(6, Map.ALL_SAME, "w"); // 6,4
  Config.addTileset(6, Map.ALL_SAME, "w"); // 6,5
  Config.addTileset(6, Map.ALL_SAME, "w"); // 6,6
  Config.addTileset(6, Map.ALL_SAME, "w"); // 6,7
  Config.addTileset(6, Map.ALL_SAME, "w"); // 6,8
  Config.addTileset(6, Map.ALL_SAME, "w"); // 6,9
  Config.addTileset(6, Map.ALL_SAME, "w"); // 6,10
  Config.addTileset(6, Map.ALL_SAME, "w"); // 6,11
  // 6,12
  Config.addTileset(6, ["wwwwwwwwxmmmmmww"
                       ,"wwwwwwwwwwwx xww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  // 6,13
  Config.addTileset(6, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwwx"]);
  // 6,14
  Config.addTileset(6, ["wwwxfffxwwxfffff"
                       ,"wwwwffffxx___fff"
                       ,"wwwwxffff[___]ff"
                       ,"wwwwwxfff[TTT]ff"
                       ,"wwwwwwfff[}t{]ff"
                       ,"wwwwwwffffffffff"
                       ,"wwwwwwffffffffff"
                       ,"wwwwwwxfffffffff"
                       ,"wwwwwwwfffffffff"
                       ,"wwwwwwxfffffffff"
                       ,"wwwwwxffffffffff"
                       ,"wwwwxffffffxxfff"
                       ,"wwwxffffffxwwwxf"
                       ,"wwwffffffxwwwwww"
                       ,"wwxfffffxwwwwwww"
                       ,"ffffffffwwwwwwww"]);
  // 6,15
  Config.addTileset(6, ["ffwwwwwwwwwwwwww"
                       ,"ffwwwwwwwwwwwwww"
                       ,"ffwwwwwwwwwwwwww"
                       ,"ffwwwwwwwwwwwwww"
                       ,"fxwwwwwwwwwwwwww"
                       ,"xwwwwwwwwwwwwwww"
                       ,"8ffxwwwwwwwwwwww"
                       ,"ffffxwwwwwwwwwww"
                       ,"fffffwwwwwwwwwww"
                       ,"fffffwwwwwwwwwww"
                       ,"fffffwwwwwwwwwww"
                       ,"fffffwwwwwwwwwww"
                       ,"ffffxwwwwwwwwwww"
                       ,"wxffwwwwwwwwwwww"
                       ,"wwffwwwwwwwwwwww"
                       ,"ww65wwwwwwwwwwww"]);
  Config.addTileset(7, Map.ALL_SAME, "w"); // 7,0
  Config.addTileset(7, Map.ALL_SAME, "w"); // 7,1
  Config.addTileset(7, Map.ALL_SAME, "w"); // 7,2
  Config.addTileset(7, Map.ALL_SAME, "w"); // 7,3
  Config.addTileset(7, Map.ALL_SAME, "w"); // 7,4
  Config.addTileset(7, Map.ALL_SAME, "w"); // 7,5
  Config.addTileset(7, Map.ALL_SAME, "w"); // 7,6
  // 7,7
  Config.addTileset(7, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwx   "
                       ,"wwwwwwwwwwwx    "
                       ,"wwwwwwwwwww     "
                       ,"wwwwwwwwwwwx    "
                       ,"wwwwwwwwwwwwx ff"
                       ,"wwwwwwwwwwwwwxff"
                       ,"wwwwwwwwwwwwwwxf"
                       ,"wwwwwwwwwwwwwwwx"]);
  // 7,8
  Config.addTileset(7, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ," xwwwwwwwwwwwwww"
                       ,"  xwwwwwwwwwwwww"
                       ,"uuuuwwwwwwwwwwww"
                       ,"uuuu   xwwwwwwww"
                       ,"ffffffff  7wwwww"
                       ,"fffffffff 5wwwww"
                       ,"fffffffffxwwwwww"
                       ,"ffffffffxwwwwwww"]);
  // 7,9
  Config.addTileset(7, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwwx"
                       ,"wwwwwwwwwwwwwx  "
                       ,"wwwwwwwwwwwwx ff"
                       ,"wwwwwwwwwwwx fff"
                       ,"wwwwwwwwwwxfffff"]);
  // 7,10
  Config.addTileset(7, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwx  xwwww"
                       ,"wwwwwwxmmmm wwww"
                       ,"wwwwwxmmmmm wwww"
                       ,"wwwwx mmcmm wwww"
                       ,"wwx        xwwww"
                       ,"wx         wwwww"
                       ,"w fffff   xwwwww"
                       ,"w ffffff xwwwwww"
                       ,"xfffffffxwwwwwww"
                       ,"ffffffffwwwwwwww"
                       ,"ffffffffwwwwwwww"
                       ,"ffffffffwwwwwwww"
                       ,"ffffffffwwwwwwww"
                       ,"fffffffxwwwwwwww"]);
  Config.addTileset(7, Map.ALL_SAME, "w"); // 7,11
  Config.addTileset(7, Map.ALL_SAME, "w"); // 7,12
  // 7,13
  Config.addTileset(7, ["wwwwwwwwwwwwwwwx"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  // 7,14
  Config.addTileset(7, ["ffffffffwwwwwwww"
                       ,"wxffffffwwwwwwww"
                       ,"wwxfffffwwwwwwww"
                       ,"wwwxfffxwwwwwwww"
                       ,"wwwwfffwwwwwwwww"
                       ,"wwwwfffwwwwwwwww"
                       ,"wwwwxffwwwwwwwww"
                       ,"wwwwwffwwwwwwwww"
                       ,"wwwwwffwwwwwwwww"
                       ,"wwwww65wwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwww87wwwwwwww"
                       ,"wwwwww  wwwwwwww"]);  
  Config.addTileset(7, Map.ALL_SAME, "w"); // 7,15  
  Config.addTileset(8, Map.ALL_SAME, "w"); // 8,0
  Config.addTileset(8, Map.ALL_SAME, "w"); // 8,1
  Config.addTileset(8, Map.ALL_SAME, "w"); // 8,2
  Config.addTileset(8, Map.ALL_SAME, "w"); // 8,3
  Config.addTileset(8, Map.ALL_SAME, "w"); // 8,4
  // 8,5
  Config.addTileset(8, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwx x"
                       ,"wwwwwwwwwwwxmmmm"
                       ,"wwwwwwwwwxmmmmmm"
                       ,"wwwwwwwwx mmmmmm"
                       ,"wwwwwwxsssssmmmx"
                       ,"wwwxsssssssssssx"
                       ,"wwwsssssssssssss"
                       ,"wwwsssssssmmssss"
                       ,"wwwssssssmmmssss"
                       ,"wwwxssssmmmmssss"
                       ,"wwwwxsssmmmmmsss"
                       ,"wwwwwsssmmmmmmmm"
                       ,"wwwwwsssmmmmmmmm"]);
  // 8,6
  Config.addTileset(8, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwxggg  f"
                       ,"wwwwwwxgggggG` f"
                       ,"wwwwxgggggggmmmm"
                       ,"wwwxgggggg`mmmmm"
                       ,"xwxggggggg*mmmmm"
                       ,"s gggggggggmmmmm"
                       ,"ssgggggggg   fff"
                       ,"ss ~ggggg   ffff"
                       ,"mmm&ggggxwxfffff"
                       ,"mmmggggxwwwffffr"
                       ,"mmm   xwwwxffffr"]);
  // 8,7
  Config.addTileset(8, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwxfffxwwwwww"
                       ,"wwwxffffffwwwwww"
                       ,"wwxfffffffwwwwww"
                       ,"xfffffffffwwwwww"
                       ,"fffffffff wwwwww"
                       ,"ffffffff  wwx xw"
                       ,"fffffmmmm xw mmx"
                       ,"mm  mmmmm  8mmmm"
                       ,"mm mmmmmm   mmmm"
                       ,"m  mmmmmDDD mmmm"
                       ,"ff  mmm DHD mmmm"
                       ,"ff       Hxwxmmm"
                       ,"ff    xwwwwwwxmm"
                       ,"rr  xwwwwwwwwwww"
                       ,"rr xwwwwwwwwwwww"]);
  // 8,8
  Config.addTileset(8, ["wwxfffffxwwwwwww"
                       ,"wwwxfffffwwwwwww"
                       ,"wwwwxffffwwwwwww"
                       ,"wwwww fffwwwwwww"
                       ,"wwwww    xwwwwww"
                       ,"wwwwx ss  wwwwww"
                       ,"wwww ssss wwwwww"
                       ,"wwwxsssssswwwwww"
                       ,"mmmmsssssswwwwww"
                       ,"mmm^sssssswwwwxm"
                       ,"mmm$ssssssxwwxmm"
                       ,"mmmmmm sss   mmm"
                       ,"mmmmmmmm   ffmmm"
                       ,"mmmmmmmm fffffmm"
                       ,"wx     fffffff  "
                       ,"wwx   ffffffffff"]);
  // 8,9
  Config.addTileset(8, ["wwwwwwwxffffffff"
                       ,"wwwwwwxfffffffff"
                       ,"wwwwwxffffffffff"
                       ,"wwwwxfffffffffff"
                       ,"wwwxffffffrrrrrr"
                       ,"wwwfffffffffffff"
                       ,"wwwfffffffffffff"
                       ,"wwxmmmmmmmmmmmmf"
                       ,"wxmmmmmmmmmmmmm "
                       ,"mmmmmmmmmmmmmmm "
                       ,"mmmmmmmmmmmmmmm "
                       ,"mmmmmmmmmmmmmmm "
                       ,"mmxxmmmmmmm     "
                       ,"mxwwwxmmmm  DDDD"
                       ,"xwwwwwwwwwwwHHHD"
                       ,"wwwwwwwwwwwwwx  "]);
  // 8,10
  Config.addTileset(8, ["rrrrrrrwwwwwwwww"
                       ,"fffrfffwwwww4www"
                       ,"fffrfffxwwww6 xw"
                       ,"fffrffffxwwwx  x"
                       ,"rrrrffffff      "
                       ,"ffffffffffdddd  "
                       ,"ffffffffffdddddd"
                       ,"fffffffff dddddd"
                       ,"ffffffffmmmddddd"
                       ,"  fffffmmmmddddd"
                       ,"mmmmmmmmmmm  fff"
                       ,"mmmmmmmmmmsssfff"
                       ,"mmmmmmmmmsssssff"
                       ,"mmmmmmmsssssss f"
                       ," mmmmmsssssssssf"
                       ," mmmmssssxwwxssf"]);
  // 8,11
  Config.addTileset(8, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"xwwwwwwwwwwwwwww"
                       ," wwwwwwwwwwwwwww"
                       ,"dxwwwwwwwwwwwwww"
                       ,"ddxwwwwwwwwwwwww"
                       ,"dddwwwwwwwwx  xw"
                       ,"dddxwwwwwwx     "
                       ,"fffffxwwwx      "
                       ,"ffffffffffffffff"
                       ,"ffffffffffffffff"
                       ,"ffffffffffffffff"
                       ,"ffffffffffffffff"
                       ,"ffffffffffffffff"]);
  // 8,12
  Config.addTileset(8, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwx  "
                       ,"wwwwwwwwwx      "
                       ,"wwwwwwwwx ffffff"
                       ,"wwwwwwwx fffffff"
                       ,"xwwwwx  ffffffff"
                       ,"  xwx ffffffffff"
                       ,"f     ffffffffff"
                       ,"ff          ffff"
                       ,"fff     xwwx fff"
                       ,"fff    xwwww  ff"
                       ,"fff   xwwwwwx  f"]);
  // 8,13
  Config.addTileset(8, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwx    7w"
                       ,"wwwwwwwwx     5w"
                       ,"x            xww"
                       ,"      xwwwwwwwww"
                       ,"  xwwwwwwwwwwwww"
                       ,"  wwwwwwwwwwwwww"
                       ,"f xwwwwwwwwwwwww"
                       ,"ff wwwwwwwwwwwww"
                       ,"ff xwwwwwwwwwwww"
                       ,"fff xwwwwwwwwwww"
                       ,"ffff  xwwwwwwwww"
                       ,"ffffff xwwwwwwww"
                       ,"fffffff xwwwwwww"
                       ,"ffffffff wwwwwww"]);
  // 8,14
  Config.addTileset(8, ["wwwwww  wwwwwwww"
                       ,"wwwwwx  wwwwwwww"
                       ,"wwwxffffwwwwwwww"
                       ,"wwxfffffwwwwwwww"
                       ,"wxffffffwwwwwwww"
                       ,"xfffffffxwwwwwww"
                       ," ffffffmmmxwwwww"
                       ," ffffffmmmmxwwww"
                       ,"xfffffmmmmmmxwww"
                       ,"wxffffmmmmmmmmm7"
                       ,"wwxfffmmmmmmmmm5"
                       ,"wwwx  mmmmmmmmxw"
                       ,"wwww   mmmmmmxww"
                       ,"wwww   mmmmmmwww"
                       ,"wwwwx    mmmmwww"
                       ,"wwwwwx    mmmwww"]);
  Config.addTileset(8, Map.ALL_SAME, "w"); // 8,15
  Config.addTileset(9, Map.ALL_SAME, "w"); // 9,0
  Config.addTileset(9, Map.ALL_SAME, "w"); // 9,1
  // 9,2
  Config.addTileset(9, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwww8  xwwwwwwx"
                       ,"wwwww1x    xwwxs"
                       ,"wwwwwwwwx  sssss"
                       ,"wwwwwwwwwwxssmmm"
                       ,"wwwwwwwwwwwssmmm"
                       ,"wwwwwwwwwwwxsssm"
                       ,"wwwwwwwwwwwwxsss"
                       ,"wwwwwwwwwwwwwxss"]);
  // 9,3
  Config.addTileset(9, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"ssxwwwwwwwwwwwww"
                       ,"sssmmmmmxwwwwwww"
                       ,"sssmmmmmmmxwwwww"
                       ,"mssssmmmmmmxwwww"
                       ,"mmssssmmmmmmxwww"
                       ,"mmssssssmmmmmxwx"
                       ,"mmssssssssmmmsss"
                       ,"ssssssssssssssss"]);
  // 9,4
  Config.addTileset(9, ["wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwwx"
                       ,"wwwwwwwwwwwwwxmm"
                       ,"wwwwwwwwwwwx  mm"
                       ,"wwwxssssssssssmm"
                       ,"wwxssssssssssssm"
                       ,"wxssssssssssssss"
                       ,"xsssssssssssssss"
                       ,"ssssssssssssssss"
                       ,"ssssssssssssssss"
                       ,"ssssssfffsssssss"
                       ,"ssssssffffssssss"
                       ,"sssssssfffssssDE"]);
  // 9,5
  Config.addTileset(9, ["wwwwwssssmmmmmmm"
                       ,"wwwwwsssssmmmmmm"
                       ,"wwwwwsssssssssss"
                       ,"wwwwxssssssssssx"
                       ,"mmmmmmmsssssssxw"
                       ,"mmmmmmmssssxwwww"
                       ,"mmmmmmxwwwwwwwww"
                       ,"mmmmmxwwwwwwwwww"
                       ,"mmmxwwwwwwwwwwww"
                       ,"mmmwwwwwwwwwwwww"
                       ,"ssxwwwwwwwwwwwww"
                       ,"sswwwwwwwwwwwwww"
                       ,"sswwwwwwwwwwwwww"
                       ,"ssxwwwwwwwwwwwww"
                       ,"   xwwwwwwwwwwww"
                       ," v  xwwwwwwwwwww"]);
  // 9,6
  Config.addTileset(9, ["mmm  xwwwwffffff"
                       ,"m   xwwwwxffffff"
                       ,"  xwwwwwx  fffff"
                       ,"wwwwwx     fffff"
                       ,"wwwx   mmm fffff"
                       ,"wwxmmmmmmm  ffff"
                       ,"wxmmmmmmmmm   ff"
                       ,"wmmmmmmmmmmmm   "
                       ,"wmmmmmmfffmmmm  "
                       ,"wmmmmm ffffmmm  "
                       ,"wmmmmmmfffff    "
                       ,"wxmmcmmfffffmmm "
                       ,"wwxfffffffmmmmmm"
                       ,"wwwffffffmmmmmmm"
                       ,"wwwxffmmmmmm xww"
                       ,"wwww  mmmmmxwwww"]);
  // 9,7
  Config.addTileset(9, ["fffwwwwwwwwwwwww"
                       ,"fffwwwwwwwwwwwww"
                       ,"ffxwwwwwwwwwwwww"
                       ,"f wwwwwwwwwwwwww"
                       ,"  wwwwwwwwwwwwww"
                       ,"  wwwwwwwwwwwwww"
                       ,"  xwwwwwwwwwwwww"
                       ,"   wwwwwwwwwwwww"
                       ,"   wwwwwwwwwwwww"
                       ,"   wwwwwwwwwwwww"
                       ,"  xwwwwwwwwwwwww"
                       ," xwwwwwwwwwwwwww"
                       ," wwwwwwwwwwwwwww"
                       ,"xwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  // 9,8
  Config.addTileset(9, ["wwwx  ffffffffff"
                       ,"wwwwx ffffffffff"
                       ,"wwwwwx ffffffff "
                       ,"wwwwww   ffff   "
                       ,"wwwwwwx         "
                       ,"wwwwwwwx        "
                       ,"wwwwwwwwx       "
                       ,"wwwwwwwwwx      "
                       ,"wwwwwwwwwwwx    "
                       ,"wwwwwwwwwwwwwwx "
                       ,"wwwwwwwwwwwwwww "
                       ,"wwwwwwwwwwwwwww "
                       ,"wwwwwwwwwwwwwwx "
                       ,"wwwwwwwwwwwwwx  "
                       ,"wwwwwwwwwwwwx   "
                       ,"wwwwwwwwwwww    "]);
  // 9,9
  Config.addTileset(9, ["xwwwwwwwwwwwww  "
                       ," wwwwwwwwwwwww m"
                       ,"xwwwwwwwwwwwwx m"
                       ,"wwwwwwwwwwwwx   "
                       ,"wwwwwwwwwwx     "
                       ,"wwwwwwwwwx      "
                       ,"xwwwwwwx    xwww"
                       ,"  xwwwx    xwwww"
                       ,"   xww4444wwwwww"
                       ,"    xx    xwwwww"
                       ,"     ffffffffxww"
                       ,"    ffffffffffxw"
                       ,"   ffffffffffffx"
                       ,"  fffff KK fffff"
                       ,"  ffffLLLLLLffff"
                       ,"  fff LLLLLL fff"]);
  // 9,10
  Config.addTileset(9, ["mmmmmssxwwwww ss"
                       ,"mmmmssxwwwwwwxss"
                       ,"mmsssxwwwwwwwxs "
                       ,"   xwwwwwwwwxfff"
                       ," xwwwwwwwwwxffff"
                       ,"xwwwwwwwwww ffff"
                       ,"wwwwwwwwwww ffff"
                       ,"wwwwwwwwwwwx    "
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"]);
  // 9,11
  Config.addTileset(9, ["ffffffffffffffff"
                       ," fffffffffffffff"
                       ,"fffffffffffffff "
                       ,"fffff   xwwwwwx "
                       ,"ffff  xwwwwwwwww"
                       ,"ffff xwwwwwwwwww"
                       ,"fff xwwwwwwwwwww"
                       ,"   xwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwwww"
                       ,"wwwwwwwwwwwwwx  "
                       ,"wwwwwwwwwwx    m"
                       ,"wwwwwwwwwx mmmmm"
                       ,"wwwwwwwww  mmmmm"
                       ,"wwwwwwwww mmmmmf"
                       ,"wwwwwwwww mmmm f"]);
  // 9,12
  Config.addTileset(9, ["ff    wwwwwwwx f"
                       ,"f    xwwwwwwwwff"
                       ,"    xwwwwwwwwwff"
                       ,"   xwwwwwwwwwxff"
                       ,"wwwwwwwwwwwwxfff"
                       ,"wwwwwwwwwwxfffff"
                       ,"wwwwwwwwwwfffff "
                       ,"wwwwwwwww8ffff  "
                       ,"wwwwwwwww6      "
                       ,"x     7wwwwwwwx "
                       ,"      5wwwwwwww "
                       ,"mmmmm wwwwwwwww "
                       ,"mmmmm xwwwwwwwww"
                       ,"mmmmm  xwwwwwww "
                       ,"fffff   xwwwwwxf"
                       ,"fffffffff      f"]);
  // 9,13
  Config.addTileset(9, ["fffffffffxwwwwww"
                       ,"ffffffffffxwwwww"
                       ,"fffffffffffwwwww"
                       ,"fffffffffffwwwww"
                       ,"f---fffffffwwwww"
                       ,"[---]fffffxwwwww"
                       ,"[UtU]   xwwwwwww"
                       ,"[}t{]   wwwwwwww"
                       ," EDD    wwwwwwww"
                       ," HHD    xwwwwwww"
                       ," H   ff mmmmmxww"
                       ," H   ffmmmmmmmmm"
                       ,"HH  fffmmmmmmmmm"
                       ," ffffffmmmmmmmmm"
                       ,"ffffff       mmm"
                       ,"fffff         mm"]);
  // 9,14
  Config.addTileset(9, ["wwwwwwx      www"
                       ,"wwwwwwwx     www"
                       ,"wwwwwwwwx    www"
                       ,"wwwwwwwww   xwww"
                       ,"wwwwwwwwx   wwww"
                       ,"wwwwwwwx    wwww"
                       ,"wwwwwww     wwww"
                       ,"wwwwwwx    xwwww"
                       ,"wwwxHI    xwwwww"
                       ,"wwx HI mmxwwwwww"
                       ,"x   7I mmwwwwwww"
                       ,"mm    mmmwwwwwww"
                       ,"mm    mmmxwwwwww"
                       ,"mm    mmmmmmxwww"
                       ,"mm      mmmmmxww"
                       ,"mm  mmm  mmmm ww"]);
  Config.addTileset(9, Map.ALL_SAME, "w"); // 9,15
  Config.addTileset(10, Map.ALL_SAME, "w"); // 10,0
  // 10,1
  Config.addTileset(10, ["wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwxmm"
                        ,"wwwwwwwwwwwwxmmm"
                        ,"wwwwwwwwwwwxmmmm"
                        ,"wwwwwwwwwwxmmmmm"
                        ,"wwwwwwwwww mmmc@"]);
  // 10,2
  Config.addTileset(10, ["wwwwwwwwwwwwwwss"
                        ,"wwwwwwwwwwwwwwxs"
                        ,"wwwwwwwwwwwwwwwx"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwwx"
                        ,"wwwwwwwwwwwwwww "
                        ,"wwwwwwwwwwwwwwx "
                        ,"wwwwwwwwwwwwwx  "
                        ,"wwwwwwwwwwwwxfff"
                        ,"wwwwwwwwwwwxffff"
                        ,"wwwwwwwwwwx ffff"
                        ,"mmmmmmmmmmmmmfff"
                        ,"mmmmmmmmmmmmmm  "
                        ,"mmmmmmmmmmmmmm  "
                        ,"mmmmmmmmmmcmm   "
                        ,"mmmmmmmmmm     x"]);
  // 10,3
  Config.addTileset(10, ["sssssssffffffsss"
                        ,"smmssssffffffsss"
                        ,"smmmsssfffffssss"
                        ," mmmssssfffsssss"
                        ," mmmmsssssssssss"
                        ,"mmmmmssssssss   "
                        ,"mmmmmsssssss xww"
                        ,"mmmmm sssss xwww"
                        ,"fmmm   sss  wwww"
                        ,"ff   mmm   xwwww"
                        ,"ffmmmmmm  xwwwww"
                        ,"fmmmmmmm  wwwwww"
                        ," mmmmmm   wwwwww"
                        ," mmmmm    wwwwww"
                        ,"xwwwwx    wwwwww"
                        ,"wwwwwwx   wwwwww"]);
  // 10,4
  Config.addTileset(10, ["ssssssssssssssDH"
                        ,"ssssssssssssssDH"
                        ,"ssssss xwwwwwwww"
                        ,"sss   xwwwwwwwww"
                        ,"s    xwwwwwwwwww"
                        ,"   xwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwww87wwwwwww"
                        ,"wwwwwwx  wwwwwww"
                        ,"wwwwwx   wwwwwww"
                        ,"wwwwx    wwwwwww"
                        ,"wwwx mm  wwwwwww"]);
  // 10,5
  Config.addTileset(10, [" vv  wwwwwwwwwww"
                        ,"    xwwwwwwwwwww"
                        ,"wwwwwww8 xwwwwww"
                        ,"wwwwwww6   xwwww"
                        ,"wwwwwwwwx     xw"
                        ,"wwwwwwwwwwx    7"
                        ,"wwwwwwwwwwwwwx 5"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"]);
  // 10,6
  Config.addTileset(10, ["wwww   mmmxwwwww"
                        ,"wwww   mmxwwwwww"
                        ,"wwwwx   xwwwwwww"
                        ,"wwwwwx xwwwwwwww"
                        ,"wwwwwwHwwwwwwwww"
                        ,"wwwwwx wwwwwwwww"
                        ,"wwwww  xwwwwwwww"
                        ,"wwwww   wwwwwwww"
                        ,"wwwww   xwwwwwww"
                        ,"wwwwwx   wwwwwww"
                        ,"wwwwwwrr xwwwwww"
                        ,"wwwwww rrrwwwwww"
                        ,"wwwwwx r  wwwwww"
                        ,"wwwww rr  xwwwww"
                        ,"wwwwx r    wwwww"
                        ,"wwwx  r rrrwwwww"]);
  Config.addTileset(10, Map.ALL_SAME, "w"); // 10,7
  // 10,8
  Config.addTileset(10, ["wwwwwwwwwwwwx   "
                        ,"wwwwwwwwwwwwwx  "
                        ,"wwwwwwwwwwwwwwwx"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"]);
  // 10,9
  Config.addTileset(10, ["  fff LLLLLL fff"
                        ,"  fff LLLLLL fff"
                        ,"  fff LLLLLL fff"
                        ,"  ffffLLLLLLffff"
                        ,"x fffff    fffff"
                        ,"w  ffff    ffff "
                        ,"wx  fff    fff  "
                        ,"ww            xw"
                        ,"wwx    DDD  xwww"
                        ,"www    DHD xwwww"
                        ,"wwwx   DHxwwwwww"
                        ,"wwww    Hwwwwwww"
                        ,"wwww   xwwwwwwww"
                        ,"wwww  xwwwwwwwww"
                        ,"wwwwxxwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"]);
  Config.addTileset(10, Map.ALL_SAME, "w"); // 10,10
  // 10,11
  Config.addTileset(10, ["wwwwwwwww  mmmmf"
                        ,"wwwwwwwwwx  mmm "
                        ,"wwwwwwwwww  mmmm"
                        ,"wwwwwwwwww  mmmm"
                        ,"wwwwwwwwwx  mmmm"
                        ,"wwwwwwwx   mmmmm"
                        ,"wwwwxmmm mmmmmmm"
                        ,"wwwxmmmmmmmmmmmm"
                        ,"wwwmmmmmmmmmmmmm"
                        ,"wwwmmmmmmmmmmmmg"
                        ,"wwwmmmmmmmmmmmm&"
                        ,"wwwmmmmmmmmmmmmg"
                        ,"wwwxmmmmmmmmmmmm"
                        ,"wwwwxmmmmmmmmmmm"
                        ,"wwwwwxmmmmmmmmmm"
                        ,"wwwwwwxmmmmmmmmm"]);
  // 10,12
  Config.addTileset(10, ["fffffffffffff   "
                        ,"ffffffffffffff  "
                        ,"ffffffffffffff  "
                        ,"mffffffffffff mm"
                        ,"mmmmmmmmmmmmmmmm"
                        ,"mmmmmmmmmmmmmmmm"
                        ,"mmmmmmmgGGGrrrrr"
                        ,"mmgggggggggmmmmm"
                        ,"ggggggggggmmmmmm"
                        ,"ggggggmmmmmmmmrr"
                        ,"ggggmmmmmmmmmmrm"
                        ,"gggmmmmmmmmmmmrm"
                        ,"~g*mmmmmmmmmmmrm"
                        ,"~gggmmmrrrrrrrrm"
                        ,"~gggmmmrmmmmmmrm"
                        ,"gggmmmmrmmmmmmrm"]);
  // 10,13
  Config.addTileset(10, ["   mmmmmmmmm    "
                        ," mmmmmmmmmmmm   "
                        ,"mmmmmmmmmmmmmm  "
                        ,"mmmmmmmmmmmmmm  "
                        ,"mmmmmmmmmmmmmmm "
                        ,"mmmmmmmmmmmmmmmm"
                        ,"rrrrrrrrrmmmmmmm"
                        ,"mmmmmmmmrmmmmmmm"
                        ,"mmmmmmmmrmmmmmmm"
                        ,"rrrrrrrrrrrrrrrr"
                        ,"mmmmmmmmmmmmmmmm"
                        ,"mmmmmmmmmmmmmmmm"
                        ,"mmrrrrmmmmmmmmmm"
                        ,"mmmmmrmmmmmmmmmm"
                        ,"mmmmmrmmmmmmmmmm"
                        ,"mmmmmrrrrrrmmmmm"]);
  // 10,14
  Config.addTileset(10, ["   mmmmm  mmmmxw"
                        ,"  mmmmmm  mmmmmx"
                        ,"  mmmmmm  mmmmmm"
                        ,"  mmmmmm   mmmmm"
                        ,"            mmmm"
                        ,"m    mmmmmm  mmm"
                        ,"mm  mmmmmmmm  mm"
                        ,"mmmmmmmmmmmmm   "
                        ,"mmmmmm   mmmmm  "
                        ,"rmmmm     mmmm  "
                        ,"rmmmmm     mmm  "
                        ,"rmmmmmmmssssssss"
                        ,"rmmmmmmmssssssss"
                        ,"rmmmmsssssssssss"
                        ,"rmmmssssssssssss"
                        ,"rmmmssssssssssss"]);
  // 10,15
  Config.addTileset(10, ["wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"xwwwwwwwwwwwwwww"
                        ,"mmxwwwwwwwwwwwww"
                        ,"mmmxwwwwwwwwwwww"
                        ,"mmmmmmxwwwwwwwww"
                        ,"mmmmmmmxwwwwwwww"
                        ,"   %mmmmwwwwwwww"
                        ,"   #mmmmwwwwwwww"
                        ,"mmmmmmmmwwwwwwww"
                        ,"mmmmmmmxwwwwwwww"
                        ,"mmmmmmxwwwwwwwww"
                        ,"s  mmmwwwwwwwwww"
                        ,"s     xwwwwwwwww"
                        ,"s      xwwwwwwww"
                        ,"sDDD     xwwwwww"]);
  Config.addTileset(11, Map.ALL_SAME, "w"); // 11,0
  // 11,1
  Config.addTileset(11, ["wwwwwwwwwx     #"
                        ,"wwwwwwwww  mmmmm"
                        ,"wwwwwwwww mmmmmm"
                        ,"wwwwwwwww mmmmmm"
                        ,"wwwwwwwww  mmmmm"
                        ,"wwwwwwwwwx  mmmm"
                        ,"wwwwwwwwwwx  mmm"
                        ,"wwwwwwwwwwwx mmm"
                        ,"wwwwwwwwwwww    "
                        ,"wwwwwwwwwwww    "
                        ,"wwwwwwwwwwwwmmmm"
                        ,"wwwwwwwwwwwwmmmm"
                        ,"wwwwwwwwwwwwxmmm"
                        ,"wwwwwwwwwwwwwmmm"
                        ,"wwwwwwwwwwwwwmcm"
                        ,"wwwwwwwwwwwww   "]);
  // 11,2
  Config.addTileset(11, ["mmmmmmmmmxwwwwww"
                        ,"mmmmmmmmxwwwwwww"
                        ,"mmmmmmmmwwwwwwww"
                        ,"mmmmmmm wwwwwwww"
                        ,"mmmmm   wwwwwwww"
                        ,"mmm    xwwwwwwww"
                        ,"mm     wwwwwwwww"
                        ,"m      wwwwwwwww"
                        ,"  mmm  wwwwwwwww"
                        ,"mmmmm  wwwwwwwww"
                        ,"mmmm  xwwwwwwwww"
                        ,"mmmm xwwwwwwwwwx"
                        ,"mmm  wwwwwwwww8 "
                        ,"m   xwwwwwwwww6 "
                        ,"   xwwwwwwwwwwww"
                        ,"xwwwwwwwwwwwwwww"]);
  // 11,3
  Config.addTileset(11, ["wwwwwwwx  xwwwww"
                        ,"wwwwwwww   wwwww"
                        ,"wwwwwwwwx  xwwwx"
                        ,"wwwwwwwwwx  xwx "
                        ,"wwwwwwwwww      "
                        ,"wwwwwwwwwx mm  m"
                        ,"wwwwwwwwx mmmmmm"
                        ,"wwwwwwwx mmmmmmm"
                        ,"wwwx     mmmmmmm"
                        ,"wwx mmmm  mmmmmm"
                        ,"x  mmmmmm mmmmmm"
                        ," mmmmmmmm    mmm"
                        ," mmmmmmmmmmm   s"
                        ,"      mmmmmmmmms"
                        ,"wwwwwx    mmmmmm"
                        ,"wwwwwwwwwx    mm"]);
  // 11,4
  Config.addTileset(11, ["wwx mmm xwwwwwww"
                        ,"wx mmmm wwwwwwww"
                        ,"  mmmmm wwwwwwww"
                        ," mmmmmsswwwwwwww"
                        ,"mmmmmssswwwwwwww"
                        ,"mmmmsssswwwwwwww"
                        ,"mmmmsssswwwwwwww"
                        ,"mmmmsssswwwwwwww"
                        ,"mmmmmssswwwwwwww"
                        ,"mmmmmssswwwwwwww"
                        ,"mcmmmmsswwwwwwww"
                        ,"sssmmmm wwwwwwww"
                        ,"sssmmmm wwwwwwww"
                        ,"ss      wwwwwwww"
                        ,"mmmm    xwwwwwww"
                        ,"mmmmm    wwwwwww"]);
  // 11,5
  Config.addTileset(11, ["wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwwx"]);
  // 11,6
  Config.addTileset(11, ["wwx rrr r  xwwww"
                        ,"wwrrr   r   xwww"
                        ,"x       rfff xww"
                        ,"     fffrffff xw"
                        ,"   rrfffJffff  x"
                        ,"x  rfffffffff   "
                        ,"wwrrfffffffff   "
                        ,"wwxfffffffffffrr"
                        ,"wwwffff ffffffr "
                        ,"wwx ffCC fffffr "
                        ,"wxfff CCffffffr "
                        ,"xfffff  ffffffr "
                        ,"ffffffrrrrrrrrr "
                        ,"fffffffffffr   x"
                        ,"fffffffffffrrrww"
                        ," fffffffff    ww"]);
  // 11,7
  Config.addTileset(11, ["wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"xwwwwwwwwwwwwwww"
                        ," wwwwwwwwwwwwwww"
                        ,"rHwwwwwwwwwwwwww"
                        ," wwwwwwwwwwwwwww"
                        ,"xwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"]);
  Config.addTileset(11, Map.ALL_SAME, "w"); // 11,8
  Config.addTileset(11, Map.ALL_SAME, "w"); // 11,9
  Config.addTileset(11, Map.ALL_SAME, "w"); // 11,10
  // 11,11
  Config.addTileset(11, ["wwwwwwwmmmmmmmmm"
                        ,"wwwwwwwmmmmmmmmm"
                        ,"wwwwwwwmmmmmmmmm"
                        ,"wwwwwwwmmmmmmmmm"
                        ,"wwwwwwwmmmrrrrrr"
                        ,"wwwwwwxmmmrmmmmm"
                        ,"wwwwwwmmmmrmmmmm"
                        ,"wwwwwwmmmmrmmmmm"
                        ,"wwwwwxmmmmrmmmmm"
                        ,"wwwwxmmmmmrrmmmm"
                        ,"wwwxmmmmmmmrmmmm"
                        ,"wwwmmmmmmmmrrrmm"
                        ,"wwwmmmmmmmmrrrmm"
                        ,"wwxmmmmmmmmrrrmm"
                        ,"wxmmmmmmmmmm~GG*"
                        ,"wmmmmmmmmmmmmmm~"]);
  // 11,12
  Config.addTileset(11, ["m mmmmmrmmmmmmrm"
                        ,"mmmmmmmrmmmmmmrm"
                        ,"mmmmmrrrmmmmmmrm"
                        ,"mmmmmrmmmmmmmmrm"
                        ,"rrrrrrmmmmmrrrrm"
                        ,"mmmmmmmmmmmmmmmm"
                        ,"mmmmmmmmmmmmmmmm"
                        ,"mmmmmcmmmmmmmmmm"
                        ,"mmmggggggggmmmmr"
                        ,"mm&gggggggg*mmmr"
                        ,"mmmggggggggmmmmr"
                        ,"mmmmmmmGmmmmmmmr"
                        ,"mmmmmmmGmmmmmmmr"
                        ,"mmmmmmmGmmmmmmmr"
                        ,"mmmmmmmGmmmmmmmr"
                        ,"GGGGGGGGmmmmmmmm"]);
  // 11,13
  Config.addTileset(11, ["mmmmmrmmmmrrrrmm"
                        ,"mmmmmrmmmmmmmrrr"
                        ,"mmmmmrmmmmmmmrmm"
                        ,"mmmmmrrrrmmmmrmm"
                        ,"mmmmmmmmrmmmrrmm"
                        ,"mmmmmmmmrmmmrmmm"
                        ,"mmmmmmmmrmmmrmmm"
                        ,"mmmmmmmmrmmmrmmm"
                        ,"mmmmmmrrrrrrrmmm"
                        ,"mmmmmmrmmmrrrrrr"
                        ,"mmmffffmmmmmmrmm"
                        ,"mmfffffmmmmmmrmm"
                        ,"mmfffffmmmmmmrmm"
                        ,"mmmfff  rrrrrrmm"
                        ,"rmmm   mmmrmmmmm"
                        ,"rmmmmmmmmmrmmmmm"]);
  // 11,14
  Config.addTileset(11, ["rmmmmsssssssssss"
                        ,"rmmmmmssssssssss"
                        ,"mmmmmmsssssssssx"
                        ,"mmmmmmsssssssxww"
                        ,"mmmmmmssssssxwww"
                        ,"mmmmmmmssssswwww"
                        ,"mmmmmmmssssxwwww"
                        ,"mmmrrrrrrrHwwwww"
                        ,"mmmrmmmm  7wwwww"
                        ,"rrrrmmmm   xwwww"
                        ,"mmmmmmmmm    xww"
                        ,"mmmmmmmmm       "
                        ,"mmmmmmmmm      x"
                        ,"mmmmmmmmm     xw"
                        ,"mmmmmmmmm     xw"
                        ,"mmmmmmmmmm mmmmx"]);
  // 11,15
  Config.addTileset(11, ["sDHD      xwwwww"
                        ," DHD       wwwww"
                        ,"wwwwx      wwwww"
                        ,"wwwww      wwwww"
                        ,"wwwww      wwwww"
                        ,"wwwww      wwwww"
                        ,"wwwww     xwwwww"
                        ,"wwwww    xwwwwww"
                        ,"wwwwx   xwwwwwww"
                        ,"wwwx   xwwwwwwww"
                        ,"www   xwwwwwwwww"
                        ,"7w8 xwwwwwwwwwww"
                        ,"1w1wwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"
                        ,"wwwwwwwwwwwwwwww"]);

  Config.setMapping({
    " " : {cssClass:"none"}
   ,"c" : {cssClass:"cave"}
   ,"d" : {cssClass:"desert", hasCorners:true, borderTile:"d"}
   ,"f" : {cssClass:"forest", hasCorners:true, hasSides:true, borderTile:"f"}
   ,"g" : {cssClass:"grass", hasCorners:true, borderTile:"goG&*~`"}
   ,"m" : {cssClass:"mountain", hasCorners:true, hasSides:true, borderTile:"90!@#$%^cm"}
   ,"o" : {cssClass:"hole"}
   ,"r" : {cssClass:"river", hasCorners:true, borderTile:"rJ"}
   ,"s" : {cssClass:"swamp", hasCorners:true, borderTile:"so:;,."}
   ,"t" : {cssClass:"town empty"}
   ,"u" : {cssClass:"ruins", block:{width:4, height:2}}
   ,"v" : {cssClass:"village"}
   ,"w" : {cssClass:"water", hasSides:true, borderTile:"wxH12345678"}
   ,"x" : {cssClass:"coastline", hasCorners:true, borderTile:"wx12345678"}
   
   ,"C" : {cssClass:"castle", block:{width:2,height:2}}
   ,"D" : {cssClass:"docks", hasCorners:true, hasSides:true, borderTile:"DEFH"}
   ,"E" : {cssClass:"docks top"}
   ,"F" : {cssClass:"waterfall"}
   ,"G" : {cssClass:"grass"}
   ,"H" : {cssClass:"water"}
   ,"I" : {cssClass:"docks right"}
   ,"J" : {cssClass:"river br"}
   ,"K" : {cssClass:"coneria castle top", block:{width:2, height:1}}
   ,"L" : {cssClass:"coneria", block:{width:6, height:6}}
   ,"M" : {cssClass:"mirage tower", block:{width:2, height:2}}
   ,"T" : {cssClass:"town"}
   ,"U" : {cssClass:"pravoka"}
   ,"V" : {cssClass:"desert caravan", hasCorners:true, borderTile:"V"}
   
   ,"1" : {cssClass:"water top"}
   ,"2" : {cssClass:"water left"}
   ,"3" : {cssClass:"water right"}
   ,"4" : {cssClass:"water bottom"}
   ,"5" : {cssClass:"coastline tl"}
   ,"6" : {cssClass:"coastline tr"}
   ,"7" : {cssClass:"coastline bl"}
   ,"8" : {cssClass:"coastline br"}
   ,"9" : {cssClass:"mountain top"}
   ,"0" : {cssClass:"mountain left"}
   ,"!" : {cssClass:"mountain right"}
   ,"@" : {cssClass:"mountain bottom"}
   ,"#" : {cssClass:"mountain tl"}
   ,"$" : {cssClass:"mountain tr"}
   ,"%" : {cssClass:"mountain bl"}
   ,"^" : {cssClass:"mountain br"}
   ,"&" : {cssClass:"grass tl"}
   ,"*" : {cssClass:"grass tr"}
   ,"~" : {cssClass:"grass bl"}
   ,"`" : {cssClass:"grass br"}
   ,":" : {cssClass:"swamp tl"}
   ,";" : {cssClass:"swamp tr"}
   ,"," : {cssClass:"swamp bl"}
   ,"." : {cssClass:"swamp br"}
   ,"+" : {cssClass:"desert tl"}
   ,"=" : {cssClass:"desert tr"}
   ,"/" : {cssClass:"desert bl"}
   ,"|" : {cssClass:"desert br"}

   ,"-" : {cssClass:"town wall top pravoka", block:{width:3, height:2}}
   ,"_" : {cssClass:"town wall top", block:{width:3, height:2}}
   ,"[" : {cssClass:"town wall left", block:{width:1, height:3}}
   ,"]" : {cssClass:"town wall right", block:{width:1, height:3}}
   ,"}" : {cssClass:"town wall gate left"}
   ,"{" : {cssClass:"town wall gate right"}
   ,")" : {}
   ,")" : {}
   ,">" : {}
   ,"<" : {}
  });
  
  var build = function($container) {
    for (var y = 0; y < this.Config.maxTilesetY(); y++) {
      var $row = $("<div/>").addClass("row");
      for (var x = 0; x < this.Config.maxTilesetX(); x++) {
        
      }
    }
  };
  
  return {
    Config: Config
   ,build: build
  };
  
})();