define(
/* CursorConstants */
function() {
  return {
    ABSTRACT_EQUIPMENT : "abstractEquipment"
   ,ABSTRACT_EQUIPMENT_ACTIONS : "abstractEquipmentActions"
   ,ARMOR_ACTIONS_MENU : "armorActions"
   ,ARMOR_MENU : "armor"
   ,BATTLE_ENEMIES : "battleEnemies"
   ,BATTLE_MENU : "battleMenu"
   ,BATTLE_PARTY : "battleParty"
   ,BATTLE_SPELLS : "battleSpells"
   ,CHAR_MENU : "charMenu"
   ,CHAR_SELECTION_MENU : "charSelectionMenu"
   ,CLINIC : "clinic"
   ,CLINIC_CHAR : "clinicChar"
   ,CLINIC_CONFIRM : "clinicConfirm"
   ,EQUIPMENT_SHOP : "equipmentShop"
   ,EQUIPMENT_SHOP_BUY_CONFIRM : "equipmentShopBuyConfirm"
   ,EQUIPMENT_SHOP_BUY_END : "equipmentShopBuyEnd"
   ,EQUIPMENT_SHOP_BUY_ITEM : "equipmentShopItem"
   ,EQUIPMENT_SHOP_SELL : "equipmentSell"
   ,EQUIPMENT_SHOP_SELL_CONFIRM : "equipmentSellConfirm"
   ,EQUIPMENT_SHOP_SELL_ITEM : "equipmentSellItem"
   ,INN : "inn"
   ,INVENTORY : "inventory"
   ,ITEM_SHOP : "itemShop"
   ,ITEM_SHOP_CONFIRM : "itemShopConfirm"
   ,ITEM_SHOP_SELECT_ITEM : "itemShopSelectItem"
   ,MAGIC_MENU : "magicMenu"
   ,MAGIC_SHOP : "magicShop"
   ,MAGIC_SHOP_CONFIRM : "magicShopConfirm"
   ,MAGIC_SHOP_SPELL : "magicShopSpell"
   ,NEW_CHAR : "newChar"
   ,NEW_CHAR_NAME : "newCharName"
   ,STATUS_MENU : "statusMenu"
   ,WEAPON_ACTIONS_MENU : "weaponActions"
   ,WEAPONS_MENU : "weapons"
  };
});